@url = http://localhost:3030/api

###
get {{url}}

###
POST {{url}}/register
Content-Type: application/json

{
	"username": "ymafqwerwew",
	"password": "123456" 
}
###
POST {{url}}/login
Content-Type: application/json

{
	"username": "ym1234",
	"password": "123456" ,
	"isadmin": true
}
###
POST {{url}}/candidate/info
Content-Type: application/json

{
}

###
POST {{url}}/company/jobpublish
Content-Type: application/json

{
	"companyid": 16,
	"jobData": {
		"职位名称": "15",
		"人数": "dsaffdg",
		"发布时间": "123",
		"任职要求": "123",
		"待遇": "123",
		"是否补助": 0,
		"联系方式": "123"
	}
}

###
POST {{url}}/collection/add
Content-Type: application/json

{
	"username": "user123",
	"collectionid": 16,
	"collectiontype": "company"
}

###
POST {{url}}/collection/remove
Content-Type: application/json

{
	"username": "user123",
	"collectionid": 16
}

###
GET {{url}}/collection/list?username=ym1234&collectiontype=job

###
POST {{url}}/job/apply
Content-Type: application/json

{
	"jobid": 8,
	"candidatename": "ym1234"
}

###
POST {{url}}/admin/approve
Content-Type: application/json

{
	"tablename": "job",
	"id": 6
}

###
GET {{url}}/job/applicationlist?candidatename=ym1234

###
GET {{url}}/admin/application?tablename=job